# https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
