[tool.poetry]
name = "Screener"
version = "0.1.0"
description = "Check e-book files for security and privacy issues."
license = "LGPL-3.0-only"
authors = ["Tom Kuson <mail@tjkuson.me>"]
repository = "https://github.com/tjkuson/screener/"

[tool.poetry.dependencies]
python = "^3.7.2"
EbookLib = "^0.17.1"
beautifulsoup4 = "^4.11.1"

[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
black = {extras = ["d"], version = "^22.10.0"}
pytest = "^7.2.0"
pylint = "^2.15.5"
coverage = "^6.5.0"
mypy = "^0.982"
types-beautifulsoup4 = "^4.11.6"

[tool.black]
line-length = 88
target-version = ["py37","py38","py39", "py310"]

[tool.isort]
profile = "black"

[[tool.mypy.overrides]]
module = ["ebooklib", "ebooklib.epub"]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
